spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/booking
    username: postgres
    password: Eldos2812
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: ReCreateBookingSystem
  mvc:
    hidden-method:
      filter:
        enabled: true
app:
  service:
    opening-hour: '09:00'
    closing-hour: '18:00'
    duration: '30'

logging:
  level:
    sql: trace